//内置对象：window对象：
//属性：
window.innerHeight 
window.innerWidth
window.pageXOffset
window.pageYOffset
window.screenX
window.screenY
window.location
window.document
window.history
window.history.length
window.screen
window.screen.width
window.screen.height
//方法：
window.alert()
window.open()
window.printf()